// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import firebase_options.dart;
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGNyTnEiBWMOKz0a3w6E7Rme0K5aktuWg',
    appId: '1:861306930882:web:682d4690a06ac53aa4dd5b',
    messagingSenderId: '861306930882',
    projectId: 'tugas2-b03f9',
    authDomain: 'tugas2-b03f9.firebaseapp.com',
    storageBucket: 'tugas2-b03f9.firebasestorage.app',
    measurementId: 'G-82KJCME1FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb-3dAGBWAtnCoFl1C1V3LsFTk7EIZ9Nc',
    appId: '1:861306930882:android:b154bc90652d6f38a4dd5b',
    messagingSenderId: '861306930882',
    projectId: 'tugas2-b03f9',
    storageBucket: 'tugas2-b03f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Mx4j0ouy6JyS8Timsnh7a5pBo3JAnNE',
    appId: '1:861306930882:ios:3983f766ed15727ea4dd5b',
    messagingSenderId: '861306930882',
    projectId: 'tugas2-b03f9',
    storageBucket: 'tugas2-b03f9.firebasestorage.app',
    iosBundleId: 'com.example.classtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Mx4j0ouy6JyS8Timsnh7a5pBo3JAnNE',
    appId: '1:861306930882:ios:3983f766ed15727ea4dd5b',
    messagingSenderId: '861306930882',
    projectId: 'tugas2-b03f9',
    storageBucket: 'tugas2-b03f9.firebasestorage.app',
    iosBundleId: 'com.example.classtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGNyTnEiBWMOKz0a3w6E7Rme0K5aktuWg',
    appId: '1:861306930882:web:3e23e0dfbd29e753a4dd5b',
    messagingSenderId: '861306930882',
    projectId: 'tugas2-b03f9',
    authDomain: 'tugas2-b03f9.firebaseapp.com',
    storageBucket: 'tugas2-b03f9.firebasestorage.app',
    measurementId: 'G-82KJCME1FN',
  );
}
